site_name: RoboSecurityArena
site_url: https://ZJUshine.github.io/RoboSecurityArena-Document
site_author: ZJUshine
docs_dir: docs
repo_url: https://github.com/ZJUshine/RoboSecurityArena
repo_name: RoboSecurityArena
theme:
  name: material
  language: zh
  icon: 
    repo: fontawesome/brands/github